basePath: /
definitions:
  entity.Alert:
    properties:
      alert_id:
        example: 1
        type: integer
      alert_message:
        example: alert message
        type: string
      metric_id:
        example: 1
        type: integer
      severity:
        example: 1
        type: integer
    type: object
  entity.AlertRecipient:
    properties:
      alert_id:
        example: 1
        type: integer
      alert_recipient_id:
        example: 1
        type: integer
      user_id:
        example: 1
        type: integer
    type: object
  entity.Metric:
    properties:
      metric_id:
        example: 1
        type: integer
      metric_name:
        example: metric name
        type: string
      metric_type_id:
        example: 1
        type: integer
      timestamp:
        example: "2006-01-02T15:04:05Z"
        type: string
      value:
        example: 0.5
        type: number
    required:
    - metric_id
    - metric_name
    - metric_type_id
    - timestamp
    - value
    type: object
  entity.MetricType:
    properties:
      type_id:
        example: 1
        type: integer
      type_name:
        example: type name
        type: string
    type: object
  entity.Role:
    properties:
      role_id:
        example: 1
        type: integer
      role_name:
        example: role name
        type: string
    type: object
  entity.User:
    properties:
      email:
        example: username@email.com
        type: string
      user_id:
        example: 1
        type: integer
      username:
        example: username
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a server for work with metrics
  termsOfService: http://swagger.io/terms/
  title: SystemMetric API
  version: "1.0"
paths:
  /api/alert-recipients:
    get:
      consumes:
      - application/json
      description: get alert recipients
      produces:
      - application/json
      responses:
        "200":
          description: Get alert recipients is successful
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - alert-recipient
    post:
      consumes:
      - application/json
      description: insert alert recipient
      parameters:
      - description: alert_id, user_id
        in: body
        name: alert-recipient
        required: true
        schema:
          $ref: '#/definitions/entity.AlertRecipient'
      produces:
      - application/json
      responses:
        "200":
          description: Insert alert recipient is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: insert page
      tags:
      - alert-recipient
  /api/alert-recipients/{id}:
    delete:
      consumes:
      - application/json
      description: delete alert recipient with alertRecipientID
      parameters:
      - description: AlertRecipient ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: delete alert recipient is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: delete page
      tags:
      - alert-recipient
    get:
      consumes:
      - application/json
      description: get alert recipient with alertRecipientID
      parameters:
      - description: AlertRecipient ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get alert recipient is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - alert-recipient
  /api/alerts:
    get:
      consumes:
      - application/json
      description: get alerts
      produces:
      - application/json
      responses:
        "200":
          description: Get alerts is successful
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - alert
    post:
      consumes:
      - application/json
      description: insert alert
      parameters:
      - description: alert_message, severity, metric_id
        in: body
        name: alert
        required: true
        schema:
          $ref: '#/definitions/entity.Alert'
      produces:
      - application/json
      responses:
        "200":
          description: Insert alert is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: insert page
      tags:
      - alert
  /api/alerts/{id}:
    delete:
      consumes:
      - application/json
      description: delete alert
      parameters:
      - description: Alert ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: delete alert is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: delete page
      tags:
      - alert
    get:
      consumes:
      - application/json
      description: get alert with alertID
      parameters:
      - description: Alert ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get alert is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - alert
  /api/metric-types:
    get:
      consumes:
      - application/json
      description: get metric types
      produces:
      - application/json
      responses:
        "200":
          description: Get metric types is successful
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - metric-type
    post:
      consumes:
      - application/json
      description: insert metric type
      parameters:
      - description: type_name
        in: body
        name: metric_type
        required: true
        schema:
          $ref: '#/definitions/entity.MetricType'
      produces:
      - application/json
      responses:
        "200":
          description: Insert metric type is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: insert page
      tags:
      - metric-type
  /api/metric-types/{id}:
    delete:
      consumes:
      - application/json
      description: delete metric type with metricTypeID
      parameters:
      - description: MetricType ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: delete metric type is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: delete page
      tags:
      - metric-type
    get:
      consumes:
      - application/json
      description: get metricType with metricTypeID
      parameters:
      - description: MetricType ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get metricType is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - metric-type
  /api/metrics:
    get:
      consumes:
      - application/json
      description: get metrics
      produces:
      - application/json
      responses:
        "200":
          description: Get metrics is successful
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - metric
    post:
      consumes:
      - application/json
      description: insert metric
      parameters:
      - description: metric_name, timestamp, value, metric_type_id
        in: body
        name: metric
        required: true
        schema:
          $ref: '#/definitions/entity.Metric'
      produces:
      - application/json
      responses:
        "200":
          description: Insert metric is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: insert page
      tags:
      - metric
    put:
      consumes:
      - application/json
      description: update value with metricID
      parameters:
      - description: metric_id, value
        in: body
        name: metric
        required: true
        schema:
          $ref: '#/definitions/entity.Metric'
      produces:
      - application/json
      responses:
        "200":
          description: Update metric is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: update page
      tags:
      - metric
  /api/metrics/{id}:
    delete:
      consumes:
      - application/json
      description: delete metric with metricID
      parameters:
      - description: Metric ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: delete metric is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: delete page
      tags:
      - metric
    get:
      consumes:
      - application/json
      description: get metric with metricID
      parameters:
      - description: Metric ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get metric is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - metric
  /api/roles:
    get:
      consumes:
      - application/json
      description: get roles
      produces:
      - application/json
      responses:
        "200":
          description: Get roles is successful
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - role
    post:
      consumes:
      - application/json
      description: insert role
      parameters:
      - description: role_name
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/entity.Role'
      produces:
      - application/json
      responses:
        "200":
          description: Insert role is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: insert page
      tags:
      - role
  /api/roles/{id}:
    delete:
      consumes:
      - application/json
      description: delete role with roleID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: delete role is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: delete page
      tags:
      - role
    get:
      consumes:
      - application/json
      description: get role with roleID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get role is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - role
  /api/users:
    get:
      consumes:
      - application/json
      description: get users
      produces:
      - application/json
      responses:
        "200":
          description: Get users is successful
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - user
    post:
      consumes:
      - application/json
      description: insert user
      parameters:
      - description: username, email
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: Insert user is successful
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: insert page
      tags:
      - user
    put:
      consumes:
      - application/json
      description: update email with userID
      parameters:
      - description: user_id, email
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: Update user is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: update page
      tags:
      - user
  /api/users/{id}:
    delete:
      consumes:
      - application/json
      description: delete user with userID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: delete user is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: delete page
      tags:
      - user
    get:
      consumes:
      - application/json
      description: get user with userID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get user is successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: get page
      tags:
      - user
swagger: "2.0"
